"""empty message

Revision ID: 83e0f67dc2f3
Revises: c65af34da0b5
Create Date: 2021-02-24 18:38:26.656356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83e0f67dc2f3'
down_revision = 'c65af34da0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'todo', ['todo'])
    op.drop_column('todo', 'ready')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('ready', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'todo', type_='unique')
    op.drop_column('todo', 'is_active')
    # ### end Alembic commands ###
